name: SimEyes
packages:
  SlideKit:
    url: https://github.com/mtj0928/SlideKit
    from: 0.3.0
targets:
  SimEyes:
    type: application
    settings:
      base:
        INFOPLIST_FILE: SimEyes/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.github.mtj0928.SlideGen.SimEyes
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    platform: macOS
    deploymentTarget: "12.0"
    sources: [SimEyes]
    dependencies:
      - package: SlideKit
