//
//  SimEyesApp.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

@main
struct SimEyesApp: App {

    /// Edit slide configurations in SlideConfiguration.swift
    private static let configuration = SlideConfiguration()

    /// A presentation content view.
    /// Edit the view here if you'd like to set environments, overlay views or background views.
    var presentationContentView: some View {
        ZStack {
            SlideRouterView(slideIndexController: Self.configuration.slideIndexController)
                .slideTheme(Self.configuration.theme)
                .foregroundStyle(.black)
                .background(.white)
//            TwitterDanmakuView()
        }
    }

    var body: some Scene {
#if os(macOS)
        WindowGroup {
            PresentationView(slideSize: Self.configuration.size) {
                presentationContentView
            }
        }
        .setupAsPresentationWindow(Self.configuration.slideIndexController, appName: "SimEyes")
        .addPDFExportCommands(for: presentationContentView, with: Self.configuration.slideIndexController, size: Self.configuration.size)

        WindowGroup {
            macOSPresenterView(
                slideSize: Self.configuration.size,
                slideIndexController: Self.configuration.slideIndexController
            ) {
                presentationContentView
            }
        }
        .setupAsPresenterWindow()
#elseif os(iOS)
        WindowGroup {
            PresentationView(slideSize: Self.configuration.size) {
                presentationContentView
            }
        }
#endif
    }
}
