//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SlideKit

struct SlideConfiguration {
    
    let size = SlideSize.standard16_9

    let slideIndexController = SlideIndexController {
        TitleSlide()
        SelfIntroductionSlide()
        CenterSlide("完全体iPhoneに興味はないか？📱")
        CenterSlide("2024年7月10日...")
        IntroductionSlide1()
        IntroductionSlide2()
        CenterSlide("茶番おしまい🍵")
        CenterSlide("シミュレーターに目を生み出してみたい\n(完全体iPhone Simulator)")
        CenterSlide("どうやって？🧐")
        CenterSlide("PCのカメラがあるじゃない💻")
        CenterSlide("実演📱")
        OverviewSlide()
        MacOSCameraToJPGSlide1()
        MacOSCameraToJPGSlide2()
        DisplayImageFromSimSlide()
        CenterSlide("完成")
        TaskSlide()
        CenterSlide("これであなたも\n完全体iPhone Simulatorに")
        CenterSlide("実用性はありませんが...")
        CenterSlide("ありがとうございました")
    }
    let theme = CustomTheme()
}

struct CustomTheme: SlideTheme {
    let headerSlideStyle = CustomHeaderSlideStyle()
    let itemStyle = CustomItemStyle()
    let indexStyle = CustomIndexStyle()
}
