//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

struct SlideConfiguration {

    /// Edit the slide size.
    let size = SlideSize.standard16_9

    ///  Add your slides into the trailing closure.
    let slideIndexController = SlideIndexController {
        TitleSlide()
        SelfIntroductionSlide()
        CenterSlide("完全体iPhoneに興味はないか？📱")
        CenterSlide("時は 2024年7月10日...")
        IntroductionSlide1()
        IntroductionSlide2()
        CenterSlide("茶番おしまい🍵")
        CenterSlide("シミュレーターにも目を生み出してみたい")
        CenterSlide("どうやって？🧐")
        CenterSlide("PCのカメラがあるじゃない💻")
        CenterSlide("実演📱")
        OverviewSlide()
        MacOSCameraToJPGSlide1()
        MacOSCameraToJPGSlide2()
        DisplayImageFromSimSlide()
        CenterSlide("完成")
        TaskSlide()
        CenterSlide("これであなたも完全体iPhoneに")
        CenterSlide("ありがとうございました")
    }
    let theme = CustomTheme()
}


struct CustomTheme: SlideTheme {
    let headerSlideStyle = CustomHeaderSlideStyle()
    let itemStyle = CustomItemStyle()
    let indexStyle = CustomIndexStyle()
}
