//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

struct SlideConfiguration {

    /// Edit the slide size.
    let size = SlideSize.standard16_9

    ///  Add your slides into the trailing closure.
    let slideIndexController = SlideIndexController {
        TitleSlide()
        SelfIntroductionSlide()
        CenterSlide("完全体iPhoneに興味はないか？")
        CenterSlide("時は 2024年7月10日...")
        IntroductionSlide1()
        IntroductionSlide2()
        CenterSlide("茶番おしまい🍵")
        CenterSlide("シミュレーターにも目を生み出してみよう")
        CenterSlide("どうやって？🧐")
        
        CenterSlide("iPhoneシミュレーターのカメラ機能を \n Macのカメラで代用して擬似的に再現した \n お話をします")
        
        CenterSlide("実演")
        
        OverviewSlide()
        
        
        CenterSlide("これであなたも完全体iPhoneに")
        
        CenterSlide("ありがとうございました")
        
        
        
    }

    let theme = CustomTheme()
}


struct CustomTheme: SlideTheme {
    let headerSlideStyle = CustomHeaderSlideStyle()
    let itemStyle = CustomItemStyle()
    let indexStyle = CustomIndexStyle()
}
